title: base

extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            header.title:
              ordering@: 0
              type: text
              autofocus: true
              label: PLUGIN_ADMIN.TITLE
              style: vertical
            
            header.master:
              ordering@: 2
              type: fieldset
              title: MH_BASIC.MASTER_HEADER
              collapsible: true
              fields:
                columns:
                  type: columns
                  fields:
                    column1:
                      type: column
                      fields:
                        header.master.text.top:
                          type: text
                          label: Top text
                          style: vertical
                        header.master.text.center:
                          type: text
                          label: Center textx
                          style: vertical
                        header.master.text.bottom:
                          type: text
                          label: bottom text
                          style: vertical
                    column2:
                      type: column
                      fields:
                        header.master.media:
                          type: file
                          label: PLUGIN_ADMIN.IMAGE
                          multiple: false
                          destination: 'user/uploads'
                          style: vertical
                          avoid_overwriting: true

